from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns=[
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/', views.contact,name='contact'),
    path('latest_jobs',views.latest_jobs,name='latest_jobs'),
    path('jobseekerreg/', views.jobseekerreg,name='jobseekerreg'),
    path('employerreg/', views.employerreg,name='employerreg'),
    path('login/', views.login, name='login'),
    path('jsreg/',views.jsreg, name='jsreg'),
    path('ereg/',views.ereg,name='ereg'),
    path('saveenq/',views.saveenq,name='saveenq'),
    path('validate/',views.validate,name='validate'),
    path('emphome/',views.emphome,name='emphome'),
    path('postjob/',views.postjob,name='postjob'),
    path('manageapp/',views.manageapp,name='manageapp'),
    path('empchangepassword/',views.empchangepassword,name='empchangepassword'),
    path('emplogout/',views.emplogout,name='emplogout'),
    path('pjob/',views.pjob,name='pjob'),
    path('joblist/',views.joblist,name='joblist'),
    path('edit_jobdetail/(?P<id>\d+)',views.edit_jobdetail,name='edit_jobdetail'),
    path('delete_job/(?P<id>\d+)',views.delete_job,name='delete_job'),
    path('delete_js/(?P<id>\d+)',views.delete_js,name='delete_js'),
    path('delete_emp/(?P<id>\d+)',views.delete_emp,name='delete_emp'),
    path('delete_enquiry/(?P<id>\d+)',views.delete_enquiry,name='delete_enquiry'),
    path('edit_news/(?P<id>\d+)',views.edit_news,name='edit_news'),
    path('change_comapnylogo/(?P<id>\d+)',views.change_companylogo,name='change_companylogo'),
    path('empchangepwd/',views.empchangepwd,name='empchangepwd'),
    path('jobhome/',views.jobhome,name='jobhome'),
    path('applyjob',views.applyjob,name='applyjob'),
    path('job_detail/(?P<id>\d+)',views.job_detail,name='job_detail'),
    path('applyforjob/(?P<id>\d+)',views.applyforjob,name='applyforjob'),
    path('jobchangepassword/',views.jobchangepassword,name='jobchangepassword'),
    path('joblogout/',views.joblogout,name='joblogout'),
    path('jobchangepwd/',views.jobchangepwd,name='jobchangepwd'),
    path('jsprofile/(?P<id>\d+)',views.jsprofile,name='jsprofile'),
    path('adminhome/',views.adminhome,name='adminhome'),
    path('adminlogout/',views.adminlogout,name='adminlogout'),
    path('enquiries/',views.enquiries,name='enquiries'),
    path('jobseekers/',views.jobseekers,name='jobseekers'),
    path('employers/',views.employers,name='employers'),
    path('addnews/',views.addnews,name='addnews'),
    path('deletenews/(?P<id>\d+)',views.deletenews,name='deletenews'),
    path('adminchangepass/',views.adminchangepass,name='adminchangepass'),
    path('adminchangepwd/',views.adminchangepwd,name='adminchangepwd'),
    path('user_profile/',views.user_profile,name='user_profile'),
    path('emp_profile/',views.emp_profile,name='emp_profile'),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)