# Generated by Django 4.1 on 2022-08-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_enquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
