# Generated by Django 4.1 on 2022-09-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0007_appliedjobs"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                ("fb_id", models.AutoField(primary_key=True, serialize=False)),
                ("rate", models.CharField(max_length=50)),
                ("msg", models.TextField()),
                ("fbdate", models.CharField(max_length=20)),
            ],
        ),
    ]
