# Generated by Django 4.1 on 2022-09-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0008_feedback"),
    ]

    operations = [
        migrations.RemoveField(model_name="feedback", name="fb_id",),
        migrations.AddField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default="1",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
