# Generated by Django 4.1 on 2022-09-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0010_rename_rate_feedback_rat"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("newstext", models.TextField()),
                ("newsdate", models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(name="Feedback",),
    ]
