# Generated by Django 4.1.5 on 2023-07-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0011_news_delete_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseeker",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
