# Generated by Django 4.1.5 on 2023-07-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0012_jobseeker_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="employer",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
