# Generated by Django 4.1.5 on 2023-07-16 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0014_rename_image_employer_image1"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs", name="end_date", field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="jobs",
            name="image",
            field=models.FileField(null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="jobs",
            name="skills",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="jobs", name="start_date", field=models.DateField(null=True),
        ),
    ]
