# Generated by Django 4.1.5 on 2023-07-16 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0015_jobs_end_date_jobs_image_jobs_skills_jobs_start_date"),
    ]

    operations = [
        migrations.RenameField(model_name="jobs", old_name="image", new_name="img",),
    ]
