# Generated by Django 4.1.5 on 2023-07-16 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0016_rename_image_jobs_img"),
    ]

    operations = [
        migrations.RemoveField(model_name="employer", name="image1",),
    ]
