# Generated by Django 4.1.5 on 2023-07-17 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0017_remove_employer_image1"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="employer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jobapp.employer",
            ),
        ),
    ]
