# Generated by Django 4.1.5 on 2023-07-17 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0018_jobs_employer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="end_date",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="jobs",
            name="start_date",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
