# Generated by Django 4.1.5 on 2023-07-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0021_remove_employer_firmwork"),
    ]

    operations = [
        migrations.RenameModel(old_name="Employer", new_name="Recruiter",),
    ]
