# Generated by Django 4.1.5 on 2023-07-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0023_rename_firmaddress_recruiter_firm_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="resume",
            field=models.FileField(null=True, upload_to=""),
        ),
    ]
