# Generated by Django 4.1.5 on 2023-07-18 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0024_appliedjobs_resume"),
    ]

    operations = [
        migrations.DeleteModel(name="AppliedJobs",),
    ]
