# Generated by Django 4.1.5 on 2023-07-18 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0026_apply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs", name="end_date", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="jobs", name="start_date", field=models.DateField(null=True),
        ),
    ]
