# Generated by Django 4.1.5 on 2023-07-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0029_appliedjobs_delete_apply"),
    ]

    operations = [
        migrations.AddField(
            model_name="appliedjobs",
            name="firmname",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
