# Generated by Django 4.1.5 on 2023-07-19 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0030_appliedjobs_firmname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="appliedjobs", old_name="firmname", new_name="firm_name",
        ),
    ]
