# Generated by Django 4.1.5 on 2023-07-19 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0036_jobseeker_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobseeker", name="user",),
    ]
