# Generated by Django 4.1.5 on 2023-07-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0041_apply_delete_appliedjobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="apply",
            name="empemailaddress",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
