# Generated by Django 4.1.5 on 2023-07-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0042_apply_empemailaddress"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobs",
            name="empemailaddress",
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
