# Generated by Django 4.1.5 on 2023-07-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0043_jobs_empemailaddress"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="empemailaddress",),
    ]
