# Generated by Django 4.1.5 on 2023-07-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobapp", "0044_remove_jobs_empemailaddress"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobs", name="employer",),
        migrations.DeleteModel(name="Apply",),
        migrations.DeleteModel(name="Jobs",),
    ]
